version: "3.9"
   
services:
  ccss_resources_db:
    image: postgres:12-alpine
    environment: 
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: 1234
        POSTGRES_DB: ccss_resources
    volumes:
      - ccss_resources_data:/var/lib/postgresql/data
    networks:
        - app

  rabbitmq:
    image: 'rabbitmq'
    ports:
        - '5672:5672'
    networks:
        - app

  ccss_resources:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.dev
    volumes:
      - .:/code
    ports:
      - "8001:8000"
    depends_on:
      - ccss_resources_db
      - ccss_resources_jobs
      - rabbitmq
    networks:
      - app

  ccss_resources_jobs:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    volumes:
      - .:/code
    ports:
      - "8002:8000"
    depends_on:
      - ccss_resources_db
      - rabbitmq
    networks:
      - app

volumes:
  ccss_resources_data:

networks:
  app:
    driver: bridge