FROM python:3
ENV PYTHONUNBUFFERED=1
WORKDIR /code
COPY requirements.txt /code/
RUN pip install -r requirements.txt
COPY . /code/

RUN chmod +x docker/start-celery.sh
ENTRYPOINT [ "/code/docker/start-celery.sh" ]