FROM python:3
ENV PYTHONUNBUFFERED=1
WORKDIR /code

COPY requirements.txt /code/
COPY . /code/

RUN pip install -r requirements.txt \
    && chmod +x docker/start-celery.sh
    
ENTRYPOINT [ "/code/start-prod.sh" ]