# Generated by Django 3.1.4 on 2021-08-12 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20210731_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multiplechoicequestion',
            name='poll',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='multiple_choice_questions', to='polls.poll'),
        ),
    ]
