# Generated by Django 3.1.4 on 2021-01-03 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("codechallenges", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="event",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="codechallenges.event",
            ),
        ),
        migrations.AddField(
            model_name="submission",
            name="question",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="codechallenges.question",
            ),
        ),
    ]
