# Generated by Django 3.1.4 on 2021-01-03 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("codechallenges", "0002_auto_20210103_1132"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="answer",
            field=models.CharField(default="", max_length=150),
            preserve_default=False,
        ),
    ]
