# Generated by Django 3.1.4 on 2021-04-30 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("codechallenges", "0003_submission_answer"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="difficulty",
            field=models.CharField(
                blank=True,
                choices=[("e", "easy"), ("m", "medium"), ("h", "hard")],
                max_length=1,
                null=True,
            ),
        ),
    ]
