# Generated by Django 3.1.4 on 2021-04-30 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("codechallenges", "0004_submission_attempts"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="submission",
            unique_together={("email", "question")},
        ),
    ]
