# Generated by Django 3.1.4 on 2021-04-30 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("codechallenges", "0004_question_difficulty"),
        ("codechallenges", "0005_auto_20210430_0158"),
    ]

    operations = []
