# Generated by Django 3.1.4 on 2021-05-22 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("codechallenges", "0007_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="questions",
        ),
        migrations.AddField(
            model_name="question",
            name="categories",
            field=models.ManyToManyField(to="codechallenges.Category"),
        ),
    ]
