# Generated by Django 3.1.4 on 2021-05-27 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("codechallenges", "0008_auto_20210522_1942"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="categories",
            field=models.ManyToManyField(blank=True, to="codechallenges.Category"),
        ),
    ]
