# Generated by Django 3.1.4 on 2021-05-25 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codechallenges', '0008_auto_20210522_1942'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=64)),
                ('lastname', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='authors',
            field=models.ManyToManyField(to='codechallenges.Author'),
        ),
    ]
