# Generated by Django 3.1.4 on 2021-06-02 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codechallenges', '0009_auto_20210525_0030'),
        ('codechallenges', '0009_auto_20210527_1757'),
    ]

    operations = [
    ]
