# Generated by Django 3.1.4 on 2021-07-31 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("codechallenges", "0013_merge_20210725_2133"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="categories",
            field=models.ManyToManyField(blank=True, to="codechallenges.Category"),
        ),
    ]
