# Generated by Django 3.1.4 on 2021-08-12 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("codechallenges", "0014_auto_20210731_1954"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="questions"),
        ),
    ]
