# Generated by Django 3.1.4 on 2021-09-05 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("codechallenges", "0014_auto_20210731_1954"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="preview",
            field=models.TextField(default="preview"),
            preserve_default=False,
        ),
    ]
