# Generated by Django 3.1.4 on 2020-12-22 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_auto_20201222_0951'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobposting',
            name='expiry_date',
        ),
    ]
