# Generated by Django 3.1.4 on 2020-12-22 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_remove_jobposting_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposting',
            name='title',
            field=models.CharField(max_length=150),
        ),
    ]
