# Generated by Django 3.1.4 on 2021-01-03 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0004_auto_20201222_1012"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobposting",
            name="country",
            field=models.CharField(max_length=150),
        ),
    ]
