# Generated by Django 3.1.4 on 2021-01-03 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0005_auto_20210103_1045"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobposting",
            name="country",
            field=models.CharField(max_length=100),
        ),
    ]
