# Generated by Django 3.1.4 on 2021-02-20 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0013_resourcepagesection_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="resourcepagesection",
            name="url",
            field=models.TextField(blank=True, null=True),
        ),
    ]
